openapi: "3.0.2"
info:
  title: Organizations Configuration Service API Swagger
  version: "1.0"
servers:
  - url: https://api.server.test/v1
paths:
  /organizations/{clientOrganizationId}:
    get:
      tags:
        - Organizations configuration
      summary: Returns a JSON object with all the organizations configurations.
      x-controller: Organizations
      operationId: getOrganizationsConfigurations
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        "200":
          description: OK
    post:
      tags:
        - Organizations configuration
      summary: Creates a JSON object with all the organizations configurations in all scopes.
      parameters:
        - in: path
          name: clientOrganizationId
          schema:
            type: string
          required: true
          description: Organization ID must be specified
      x-controller: Organizations
      operationId: createOrganizationsConfiguration
      x-authorizationRequired: true
      requestBody:
        description: The object will contain the changes to organizations configurations in all scopes.
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - type: object
                  title: scopes
                  properties:
                    scopes:
                      type: object
                      minProperties: 1
                  required: ["scopes"]
                - type: object
                  title: ventures
                  properties:
                    ventures:
                      type: object
                      minProperties: 1
                  required: ["ventures"]
      responses:
        "200":
          description: OK
    patch:
      tags:
        - Organizations configuration
      summary: Updates a JSON object with all the organizations configurations in all scopes.
      x-controller: Organizations
      operationId: updateOrganizationsConfiguration
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the changes to organizations configurations in all scopes.
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - type: object
                  title: scopes
                  properties:
                    scopes:
                      type: object
                      minProperties: 1
                  required: ["scopes"]
                - type: object
                  title: ventures
                  properties:
                    ventures:
                      type: object
                      minProperties: 1
                  required: ["ventures"]
      responses:
        "200":
          description: OK
    put:
      tags:
        - Organizations configuration
      summary: Fully updates a JSON object with all the organizations configurations in all scopes.
      x-controller: Organizations
      operationId: fullUpdateOrganizationsConfiguration
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the organizations configurations in all scopes.
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - type: object
                  title: scopes
                  properties:
                    scopes:
                      type: object
                      minProperties: 1
                  required: ["scopes"]
                - type: object
                  title: ventures
                  properties:
                    ventures:
                      type: object
                      minProperties: 1
                  required: ["ventures"]
      responses:
        "200":
          description: OK
    delete:
      tags:
        - Organizations configuration
      summary: Deletes the organization configuration.
      x-controller: Organizations
      operationId: deleteOrganizationsConfiguration
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        "200":
          description: OK

  /organizations/{clientOrganizationId}/ventures/{ventureId}:
    get:
      tags:
        - Organizations configuration
      summary: Returns a JSON object with all the venture’s configurations in a specific organization.
      x-controller: Organizations
      operationId: getOrganizationsConfigurationsVentures
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        "200":
          description: OK
    post:
      tags:
        - Organizations configuration
      summary: Create the venture object.
      x-controller: Organizations
      operationId: createOrganizationsConfigurationVentures
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the changes to venture's configurations in all scopes.
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
      responses:
        "200":
          description: OK
    patch:
      tags:
        - Organizations configuration
      summary: Update the venture object.
      x-controller: Organizations
      operationId: updateOrganizationsConfigurationVentures
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the changes to venture's configurations in all scopes.
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
      responses:
        "200":
          description: OK
    put:
      tags:
        - Organizations configuration
      summary: Fully updates a JSON object with all the organizations venture’s configurations in all scopes.
      x-controller: Organizations
      operationId: fullUpdateOrganizationVenuteConfiguration
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the organizations configurations in all scopes.
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - type: object
                  title: scopes
                  properties:
                    scopes:
                      type: object
                      minProperties: 1
                  required: ["scopes"]
                - type: object
                  title: ventures
                  properties:
                    ventures:
                      type: object
                      minProperties: 1
                  required: ["ventures"]
      responses:
        "200":
          description: OK
    delete:
      tags:
        - Organizations configuration
      summary: Deletes an organization’s configuration in a specific venture.
      x-controller: Organizations
      operationId: deleteOrganizationsConfiguration_ventures
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        "200":
          description: OK

  /organizations/{clientOrganizationId}/scopes/{scope}:
    get:
      tags:
        - Organizations configuration
      summary: Returns a JSON object with all the organization’s configurations in a specific scope. Possible URL Parameter withShared – Boolean that controls the shared configuration doc in the response.
      x-controller: Organizations
      operationId: getOrganizationsConfigurationsScopes
      parameters:
        - in: query
          name: withShared
          schema:
            type: boolean
            default: false
          description: Boolean that controls the shared configuration doc in the response
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        "200":
          description: OK
    post:
      tags:
        - Organizations configuration
      summary: Returns the scope object which has been changed.
      x-controller: Organizations
      operationId: createOrganizationsConfigurationScopes
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the changes to scopes's configurations in the specific organizaion.
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
      responses:
        "200":
          description: OK
    patch:
      tags:
        - Organizations configuration
      summary: Returns the scope object which has been changed.
      x-controller: Organizations
      operationId: updateOrganizationsConfigurationScopes
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the changes to venture's configurations in all scopes.
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
      responses:
        "200":
          description: OK
    put:
      tags:
        - Organizations configuration
      summary: Get Updated Configuration and create new record with the latest version - Returns the scope object which has been changed.
      x-controller: Organizations
      operationId: fullUpdateOrganizationsConfiguration_scopes
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain updated configuration for the given scope.
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
      responses:
        "200":
          description: OK
    delete:
      tags:
        - Organizations configuration
      summary: Deletes an organization’s configuration in a specific scope.
      x-controller: Organizations
      operationId: deleteOrganizationsConfiguration_scopes
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        "200":
          description: OK

  /organizations/{clientOrganizationId}/ventures/{ventureId}/scopes/{scope}:
    get:
      tags:
        - Organizations configuration
      summary: Returns a JSON object with all the organization’s configurations in a specific scope. Possible URL Parameter withShared – Boolean that controls the shared configuration doc in the response.
      x-controller: Organizations
      operationId: getOrganizationsConfigurationsVenturesScopes
      parameters:
        - in: query
          name: withShared
          schema:
            type: boolean
            default: false
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        "200":
          description: OK
    post:
      tags:
        - Organizations configuration
      summary: Returns the scope object which has been changed.
      x-controller: Organizations
      operationId: createOrganizationsConfigurationVenturesScopes
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the changes to scopes's configurations in the specific organizaion.
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
      responses:
        "200":
          description: OK
    patch:
      tags:
        - Organizations configuration
      summary: Returns the scope object which has been changed.
      x-controller: Organizations
      operationId: updateOrganizationsConfigurationVenturesScopes
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: The object will contain the changes to venture's configurations in all scopes.
        required: true
        content:
          application/json:
            schema:
              type: object
              minProperties: 1
      responses:
        "200":
          description: OK
    delete:
      tags:
        - Organizations configuration
      summary: Deletes an organization’s configuration in a specific scope in a specific venture.
      x-controller: Organizations
      operationId: deleteOrganizationsConfiguration_ventures_scopes
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: ventureId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      responses:
        "200":
          description: OK
  /organizations/{clientOrganizationId}/assets/images:
    post:
      tags:
        - Images
      summary: Returns the image ID and URL.
      x-controller: Assets
      operationId: createImageAsset
      parameters:
        - name: clientOrganizationId
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
      requestBody:
        description: A binary data representing an image.
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              minProperties: 1
              properties:
                file:
                  type: string
                  format: binary
                  maxLength: 2048
            encoding:
              file:
                contentType: image/apng, image/bmp, image/gif, image/x-icon, image/jpeg, image/png
      responses:
        "201":
          description: Asset created
  /scopes/{scope}:
    get:
      tags:
        - Internal
      summary: Returns a JSON object with all the organizations configurations.
      x-controller: Scopes
      operationId: getOrganizationsScopeConfigurations
      parameters:
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: withoutVentureId
          in: query
          required: false
          schema:
            type: string
            maxLength: 80
      responses:
        "200":
          description: OK
  /scopes:
    get:
      tags:
        - Internal
      summary: Returns a JSON object with all the organizations configurations.
      x-controller: Scopes
      operationId: getScopesConfigurations
      parameters:
        - name: withoutVentureId
          in: query
          required: false
          schema:
            type: string
            maxLength: 80
        - name: scope
          in: query
          required: false
          schema:
            type: array
          explode: false
          style: form
          allowReserved: true
          description: support multiple scopes separated by commas, template - ?scope=a,b,c
      responses:
        "200":
          description: OK
  /schemas:
    get:
      tags:
        - Internal
      summary: Returns a JSON object with all the scopes schema configurations.
      x-controller: Schemas
      operationId: getConfigurationSchemas
      responses:
        "200":
          description: OK
  /schemas/{scope}:
    get:
      tags:
        - Internal
      summary: Returns a JSON object with the Schema configurations within that scope.
      x-controller: Schemas
      operationId: getConfigurationSchemaByScope
      parameters:
        - name: scope
          in: path
          required: true
          schema:
            type: string
            maxLength: 255
        - name: withShared
          in: query
          schema:
            type: boolean
            default: false
      responses:
        "200":
          description: OK
